
package com.donc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestService", targetNamespace = "http://donc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "testMethod", targetNamespace = "http://donc.com/", className = "com.donc.client.TestMethod")
    @ResponseWrapper(localName = "testMethodResponse", targetNamespace = "http://donc.com/", className = "com.donc.client.TestMethodResponse")
    @Action(input = "http://donc.com/TestService/testMethodRequest", output = "http://donc.com/TestService/testMethodResponse")
    public void testMethod(
        @WebParam(name = "arg0", targetNamespace = "")
        TestRequestObj arg0);

}
